const express = require("express");
const app = express();
const cookieParser = require("cookie-parser");
app.listen(process.env.PORT || 8080, () => {
  console.log(`Port : ${process.env.PORT}`.red);
});
const cors = require("cors");
const dotenv = require("dotenv");
const connectDatabase = require("./config/dbCon");
const userRoute = require("./Routes/User");
const productRoute = require("./Routes/Product");
dotenv.config({ path: "./config/.env" });
const conString = process.env.DB_URI;
require("colors");
connectDatabase({ conString });
app.use(cookieParser());
app.use(express.json());
app.use(cors());
app.use("/api/v1", userRoute);
app.use("/api/v1", productRoute);
